# this file contains user-facing config settings;
# internal application settings in .appsettings.yaml

# logzero log level: CRITICAL (less messages), ERROR, WARNING, INFO, DEBUG (more messages)
loglevel: DEBUG

# runtime settings
runtime:
  name: pytest
  #uuid: # leave blank to generate a new uuid; or set a fixed uuid value
  uuid: 5b66b33e-5dab-4158-8b50-b4363b67fd16 # this would make the runtime have a fixed uuuid
  reg_attempts: 0 # 0 = infinite
  reg_timeout_seconds: 5
  reg_fail_error: false  
  max_nmodules: 100
  ka_interval_sec: 60
  realm: realm

# mqtt username and password in .secrets.yaml
mqtt:
  host: mqtt.arenaxr.org
  port: 8883
  ssl: true

#mqtt:
#  host: arena-dev1.conix.io
#  port: 11883
#  ssl: false

# where/how we keep program files;
# these might change, depending on class defined in .appsettings.yaml
repository:
  url: https://arenaxr.org/store

# launcher config; what starts modules
launcher:
  # launcher general settings
  pipe_stdout: true
  # these will be added to env passed to module
  env: 
    ENABLE_INTERPRETER=1
