# this file contains user-facing config settings;
# internal application settings in .appsettings.yaml
version: 0.1

# logzero log level: CRITICAL (less messages), ERROR, WARNING, INFO, DEBUG (more messages)
loglevel: DEBUG

# runtime settings
runtime:
  name: arena-rt1
  namespace: public
  uuid: cb65196b-0537-4364-939a-87d004babd4c # this will make the runtime have a fixed uuuid; comment to generate a new one
  reg_attempts: -1 # -1 = skip registration; 0 = infinite
  reg_timeout_seconds: 5
  reg_fail_error: false
  max_nmodules: 100
  realm: realm
  ka_interval_sec: 20
  is_orchestration_runtime: false
  tags: ["arena-py", "containerized-modules"] 

# mqtt username and password in .secrets.yaml
mqtt:
  host: arena0.andrew.cmu.edu
  port: 8883
  ssl: true

#mqtt:
#  host: arena-dev1.conix.io
#  port: 11883
#  ssl: false

# where/how we keep program files;
# these might change, depending on class defined in .appsettings.yaml
repository:
  url: https://arenaxr.org/store/users/

# launcher config; what starts modules
launcher:
  # launcher general settings
  pipe_stdout: true
  # these will be added to env passed to module
  env: 
    ENABLE_INTERPRETER=1
