# this file contains user-facing config settings;
# internal application settings in .appsettings.yaml

# logzero log level: CRITICAL (less messages), ERROR, WARNING, INFO, DEBUG (more messages)
loglevel: DEBUG

# runtime settings
runtime:
  name: containerized-runtime
  #uuid: # leave blank to generate a new uuid; or set a fixed uuid value
  uuid: cb65196b-0537-4364-939a-87d004babd4c # this would make the runtime have a fixed uuuid
  reg_attempts: 0 # 0 = infinite
  reg_timeout_seconds: 5
  max_nmodules: 100
  realm: realm

# mqtt username and password in .secrets.yaml
mqtt:
  host: arena-dev1.conix.io
  port: 8883
  ssl: true

#mqtt:
#  host: arena-dev1.conix.io
#  port: 11883
#  ssl: false

# where/how we keep program files;
# these might change, depending on class defined in .appsettings.yaml
repository:
  url: https://arena-dev1.conix.io/store

# launcher config; what starts modules
launcher:
  # launcher general settings
  pipe_stdout: true

