# this file contains user-facing config settings;
# internal application settings in .appsettings.yaml

# logzero log level: CRITICAL (less messages), ERROR, WARNING, INFO, DEBUG (more messages)
loglevel: DEBUG

# runtime settings
runtime:
  name: containerized-runtime
  #uuid: # leave blank to generate a new uuid; or set a fixed uuid value
  uuid: 0b99e423-e94e-435d-8e75-a3a3bf19a1c8 # this would make the runtime have a fixed uuuid
  reg_attempts: 0 # -1 = skip registration; 0 = infinite
  reg_timeout_seconds: 5
  reg_fail_error: false # registration failure causes the runtime to exit  
  max_nmodules: 100
  ka_interval_sec: 5
  realm: realm

# mqtt username and password in .secrets.yaml, if used 
# username and password default to "" if not defined in .secrets.yaml
mqtt:
  host: broker.hivemq.com
  port: 1883
  ssl: false

# where/how we keep program files;
# these might change, depending on class defined in .appsettings.yaml
repository:
  url: https://localhost/store

# launcher config; what starts modules
launcher:
  # launcher general settings
  pipe_stdout: true

