# internal, developer-facing application settings
# ** a *normal* user will normally not edit this file **

dynaconf_merge: true # merge with config in settings.yaml (required)

# launcher config; what starts modules
# add launchers (a Launcher-derived class) here; launcher key is the create request filetype (WA, PY, ...)
launcher:
  # space-separated list e.g.: python:python3 wasm:wasi_preview_1;
  # union of apis supported by all configured launchers below
  apis: python:python3 wasm:wasi_preview_1
  PY: # launcher key
    class: launcher.python_launcher.PythonLauncher # instanciate a Launcher-derived class from: module.submodule.Class
    # launcher-specific (launcher.python_launcher) arguments
    docker: # this launcher uses docker with these options
      # use this image
      image: python
      dft_qos: # default qos options
        # 25% of 1 cpu to each container
        cpu_count: 1
        cpu_period: 100000
        cpu-quota: 25000
      run_opts: # run options
        auto_remove: True
        stdin_open: True
        detach: True
        cap-drop: all

  WA: # launcher key
    class: launcher.wasm_launcher.WasmLauncher # instanciate a Launcher-derived class from: module.submodule.Class
    # launcher-specific (launcher.wasm_launcher) arguments
    image: python
  # other examples TODO
  #CTN: # launcher key
    #class: launcher.container_launcher.ContainerLauncher # instanciate a Launcher-derived class from: module.submodule.Class
    #launcher-specific (launcher.container_launcher) arguments
    #...
  #PY: # launcher key (another way to start python programs)
    #class: launcher.scripted-native-launcher.NativeLauncher # instanciate a Launcher-derived class from: module.submodule.Class
    # launcher-specific (docker.launcher.py) arguments
    #script_path: runtimemngr/py_run.sh
    #pipe_stdin_stdout: true

runtime:
  apis: "@format {this.launcher.apis}" #apis from launcher config

# topics used by runtime
# realm and uuid (defined in runtime section - in settings.yaml) are replaced by values
topics:
  reg: "@format {this.runtime.realm}/proc/reg" # OLD; to remove
  ctl: "@format {this.runtime.realm}/proc/control/{this.runtime.uuid}" # OLD; to remove
  runtimes: "@format {this.runtime.realm}/proc/runtimes"
  modules: "@format {this.runtime.realm}/proc/modules/{this.runtime.uuid}"
  dbg: "@format {this.runtime.realm}/proc/debug/{this.runtime.uuid}"
  stdout: "@format {this.runtime.realm}/proc/debug/{this.runtime.uuid}/stdout"
  stdin: "@format {this.runtime.realm}/proc/debug/{this.runtime.uuid}/stdin"
  stderr: "@format {this.runtime.realm}/proc/debug/{this.runtime.uuid}/stderr"

# where/how we keep program files
repository:
  class: program_files.filestore_builder.FileStoreBuilder # instanciate a Repo bouilder class from: module.submodule.Class
