on:
  push:
    branches:
      - main
name: release-please
jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: googleapis/release-please-action@d1a8f221d7723166f48a584aebba00ef3f6febec # v4.1.4
        id: release
        with:
          release-type: simple
      # The logic below handles the publication to docker hub
      - name: Login to Docker Hub
        if: ${{ steps.release.outputs.release_created }}
        uses: docker/login-action@dd4fa0671be5250ee6f50aedf4cb05514abda2c7 # v1.14.1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      - name: Checkout code
        if: ${{ steps.release.outputs.release_created }}  
        uses: actions/checkout@a37ce9120846195fa4ece8f58b268e6043cb2f26 # v3.7.0
        with:
            fetch-depth: 0
      - name: Get release
        if: ${{ steps.release.outputs.release_created }}
        id: get_release
        uses: WyriHaximus/github-action-get-previous-tag@04e8485ecb6487243907e330d522ff60f02283ce # v1.4.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push Docker image
        if: ${{ steps.release.outputs.release_created }}      
        id:   docker_build
        uses: docker/build-push-action@ac9327eae2b366085ac7f6a2d02df8aa8ead720a # v2.10.0
        with:
          build-args: |
            chash=${{ github.sha }}
            version=${{ steps.get_release.outputs.tag }}
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/${{ github.event.repository.name }}:latest, ${{ secrets.DOCKER_HUB_USERNAME }}/${{ github.event.repository.name }}:${{ steps.get_release.outputs.tag }}
      - name: Image digest
        if: ${{ steps.release.outputs.release_created }}
        run: echo ${{ steps.docker_build.outputs.digest }}
      
